version: '3.4'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: playground-nginx
    ports:
        - '8080:80'
        - '8000:443'
    volumes:
        - '/var/run/docker.sock:/tmp/docker.sock:ro'
        - './shared/nginx/certs:/etc/nginx/certs:ro'
    networks:
        proxy: null
        playground:
            aliases:
                - blog-api.playground.local
                - playground-gateway.playground.local
    restart: always

  blogdb:
    image: postgres
    volumes:
         - postgres_data:/var/lib/postgresql/data/

  blog.webapi:
    image: ${DOCKER_REGISTRY-}blogwebapi
    environment:
      - VIRTUAL_HOST=blog-api.playground.local
    build:
      context: .
      dockerfile: src/Services/Blog/Blog.WebApi/Dockerfile

  playground.apiocelotgw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    environment:
      - VIRTUAL_HOST=playground-gateway.playground.local
    build:
      context: .
      dockerfile: src/ApiGateways/Playground.OcelotApiGw/Dockerfile

volumes:
    postgres_data:

networks:
    proxy:
        name: playgroundidentityserver_proxy
        driver: bridge
    playground:
        name: playgroundidentityserver_identityserverui
        driver: bridge
