version: '3.4'

services:   
  blogdb:
    image: postgres
    volumes:
         - postgres_data:/var/lib/postgresql/data/

  blog.webapi:
    image: ${DOCKER_REGISTRY-}blogwebapi
    build:
      context: .
      dockerfile: src/Services/Blog/Blog.WebApi/Dockerfile

volumes:
  postgres_data: