version: '3.4'

services:
    blogdb:
        container_name: blogdb
        restart: always
        environment:
            - POSTGRES_USER=baonguyen
            - POSTGRES_PASSWORD=P@ss123
            - POSTGRES_DB=BlogDb
        ports:
            - "5432:5432"

    blog.webapi:
        container_name: blog.webapi
        environment:
            - VIRTUAL_HOST=blog-api.playground.local
            - DockerConfiguration__UpdateCaCertificate=true
            - ASPNETCORE_ENVIRONMENT=Development
            #- ASPNETCORE_URLS=https://+:443;http://+:80
            #- ASPNETCORE_Kestrel__Certificates__Default__Password=B@0probmt955
            #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp-web-api.pfx
            - "ConnectionStrings:postgres=Host=blogdb;Port=5432;Username=baonguyen;Password=P@ss123;Database=BlogPostgres"
            - "SwaggerConfig:AuthorizationBaseUrl=https://sts.skoruba.local"
            - "IdentityServer:AuthorityUrl=https://sts.skoruba.local"
            - "IdentityServer:RequireHttps=false"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - './shared/nginx/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt'
            #- ./src/certs/Api:/https/
            #- type: bind # Using a bind volume as only this single file from `certs` directory should end up in the container.
            #  source: ./src/certs/aspnetapp-root-cert.cer
            #  target: /https-root/aspnetapp-root-cert.cer
        depends_on:
            - blogdb
        networks:
          playground: null
        #ports:
        #    - "7000:80"
        #    - "8000:443"
            
    playground.apiocelotgw:
        container_name: ocelotapigw
        environment:
            - VIRTUAL_HOST=playground-gateway.playground.local
            - DockerConfiguration__UpdateCaCertificate=true
            - ASPNETCORE_ENVIRONMENT=Development
            #- ASPNETCORE_URLS=https://+:443;http://+:80
            #- ASPNETCORE_Kestrel__Certificates__Default__Password=B@0probmt955
            #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp-web-api.pfx
            - "IdentityServer:AuthorityUrl=https://sts.skoruba.local"
            - "IdentityServer:RequireHttps=false"
            #- "ElasticConfiguration:Uri=http://es01:9200"
        volumes:
            - './shared/nginx/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt'
            #- ./src/certs/Api:/https/
            #- type: bind # Using a bind volume as only this single file from `certs` directory should end up in the container.
            #  source: ./src/certs/aspnetapp-root-cert.cer
            #  target: /https-root/aspnetapp-root-cert.cer
        depends_on:
            - blog.webapi
        networks:
          playground: null
        #ports:
        #    - "7048:80"
        #    - "8048:443"
